description: Common Training params
exclude: True
properties:
  dataset:
    description: Dataset for training
    title: Dataset
    type: dataset
  base_model:
    description: Base model for training
    title: Base Model
    type: model
title: Commons
type: object
