description: LLM HumanEval
inherits:
  - config/eval/common.yaml
outputs:
  result:
    description: Evaluation results
    title: Result
    type: string
properties:
  n_sample:
    default: 1
    description: Number of samples to generate per prompt
    title: N Samples
    type: integer
  load_8bit:
    default: true
    description: Use 8-bit precision
    title: Load 8bit
    type: boolean
